### ISSUE TITLE
TTGO T-Watch GFX Plus sketch problem

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [moononournation/TTGO-T-Watch#1]
Hello i have the TTGO t-watch 2020 i believe that is what it's called. I got a small error when i tryed to compile the sketch i got a error saying Missing Arduino_GFX_Library. So i found your library and installed it. When i did i got this error.

`WARNING: Category '' in library GFX Library for Arduino is not valid. Setting to 'Uncategorized'
C:\Users\JJCSYS~1\AppData\Local\Temp\arduino_modified_sketch_102088\Arduino-T-Watch-GFX-Plus.ino:27:21: fatal error: pcf8563.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board TTGO T-Watch.`

I'm not sure what to do or how to fix this. Can you help me please?

Joseph

**Comment by Kaki-In** [comment]
If I am not wrong, you surely have to install the TFT_eSPI library

**Comment by Therealjosephchrzempiec** [comment]
hello Thnak you, This was over a year ago. I manage to get it working.
